// Frontend display config for Season 1 Battle Pass.
// Mirrors server/config/season1.js — server owns validation/points;
// this file owns display data (icons, names, mission text).

export const SEASON1_LEVELS = [
  {
    level: 1,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Primera Partida',       desc: 'Juega 1 partida en cualquier modo',                              enabled: true  },
    proReward:   { type: 'xp',             amount: 500 },
  },
  {
    level: 2,
    freeMission: { title: 'Primera Partida',       desc: 'Juega 1 partida en cualquier modo',                              enabled: true  },
    freeReward:  { type: 'xp',             amount: 300 },
    proMission:  { title: 'Desafíos Iniciales',    desc: 'Completa 5 Daily Challenges',                                    enabled: true  },
    proReward:   { type: 'badge',          name: 'Early Trader',        emoji: '📊' },
  },
  {
    level: 3,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Victorias Classic',     desc: 'Gana 15 rondas en Classic Mode',                                 enabled: true  },
    proReward:   { type: 'username_color', id: 'color_green',  name: 'Verde',  hex: '#22c55e' },
  },
  {
    level: 4,
    freeMission: { title: 'Desafíos Diarios',      desc: 'Completa 3 Daily Challenges',                                    enabled: true  },
    freeReward:  { type: 'title',          name: 'Market Watcher' },
    proMission:  { title: 'Survival Inicial',      desc: 'Sobrevive 30 rondas en Survival',                                enabled: true  },
    proReward:   { type: 'xp',             amount: 750 },
  },
  {
    level: 5,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Stop Loss & TP',        desc: 'Usa Stop Loss y Take Profit en una misma operación',             enabled: false },
    proReward:   { type: 'ticket',         name: 'Restauración de Racha' },
  },
  {
    level: 6,
    freeMission: { title: 'Primera Posición',      desc: 'Abre tu primera posición en Trading Mode',                       enabled: false },
    freeReward:  { type: 'xp',             amount: 500 },
    proMission:  { title: 'Duelos en Arena',       desc: 'Gana 5 duelos en Arena contra jugadores reales',                 enabled: true  },
    proReward:   { type: 'badge',          name: 'Elite',               emoji: '⭐' },
  },
  {
    level: 7,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Racha Classic',         desc: 'Acierta 10 rondas seguidas en Classic',                          enabled: true  },
    proReward:   { type: 'xp',             amount: 1000 },
  },
  {
    level: 8,
    freeMission: { title: 'Survival Básico',       desc: 'Sobrevive 20 rondas en Survival',                                enabled: true  },
    freeReward:  { type: 'title',          name: 'Chart Reader' },
    proMission:  { title: 'Ranking Semanal',       desc: 'Llega al top 50 del ranking semanal',                            enabled: true  },
    proReward:   { type: 'username_color', id: 'color_gold',   name: 'Dorado', hex: '#f5c842' },
  },
  {
    level: 9,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Survival Avanzado',     desc: 'Sobrevive 75 rondas en Survival',                                enabled: true  },
    proReward:   { type: 'avatar', id: 'avatar_fox',    name: 'Fox' },
  },
  {
    level: 10,
    freeMission: { title: 'Racha de Desafíos',     desc: 'Completa 7 Daily Challenges seguidos',                           enabled: true  },
    freeReward:  { type: 'xp',             amount: 750 },
    proMission:  { title: 'Constancia Diaria',     desc: 'Completa 14 Daily Challenges seguidos',                          enabled: true  },
    proReward:   { type: 'mechanic', id: 'mechanic_portfolio_view',   name: 'Ver Portfolio' },
  },
  {
    level: 11,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: '4 Categorías',          desc: 'Opera en las 4 categorías (cripto, materias, índices, acciones)', enabled: false },
    proReward:   { type: 'xp',             amount: 1500 },
  },
  {
    level: 12,
    freeMission: { title: 'Historical Mode',       desc: 'Completa un evento en Historical Mode',                          enabled: true  },
    freeReward:  { type: 'title',          name: 'Risk Taker' },
    proMission:  { title: 'Historical Completo',   desc: 'Completa todos los eventos de Historical Mode',                  enabled: true  },
    proReward:   { type: 'ticket',         name: 'Restauración de Racha' },
  },
  {
    level: 13,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Ranking Top 25',        desc: 'Llega al top 25 del ranking semanal',                            enabled: true  },
    proReward:   { type: 'badge',          name: 'Season 1 Pro',        emoji: '🌟' },
  },
  {
    level: 14,
    freeMission: { title: 'Ganancia Trading',      desc: 'Cierra una posición con al menos +1% de ganancia',               enabled: false },
    freeReward:  { type: 'xp',             amount: 1000 },
    proMission:  { title: 'Racha Classic',         desc: 'Acierta 15 rondas seguidas en Classic',                          enabled: true  },
    proReward:   { type: 'theme',          name: 'Midnight' },
  },
  {
    level: 15,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Racha 21 Días',         desc: 'Mantén una racha de 21 días',                                    enabled: true  },
    proReward:   { type: 'xp',             amount: 2000 },
  },
  {
    level: 16,
    freeMission: { title: 'Racha Classic',         desc: 'Acierta 5 rondas seguidas en Classic',                           enabled: true  },
    freeReward:  { type: 'title',          name: 'Bull Runner' },
    proMission:  { title: 'Duelos en Arena',       desc: 'Gana 20 duelos en Arena contra jugadores reales',                 enabled: true  },
    proReward:   { type: 'username_color', id: 'color_red',    name: 'Rojo',   hex: '#e05555' },
  },
  {
    level: 17,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: '15 Operaciones +1%',    desc: 'Cierra 15 operaciones con +1% o más cada una',                   enabled: false },
    proReward:   { type: 'xp',             amount: 2500 },
  },
  {
    level: 18,
    freeMission: { title: 'Historical Avanzado',   desc: 'Completa 3 eventos en Historical Mode',                          enabled: true  },
    freeReward:  { type: 'xp',             amount: 1500 },
    proMission:  { title: 'Racha de Desafíos',     desc: 'Completa 30 Daily Challenges seguidos',                          enabled: true  },
    proReward:   { type: 'ticket',         name: 'Restauración de Racha' },
  },
  {
    level: 19,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Ranking Top 10',        desc: 'Llega al top 10 del ranking semanal',                            enabled: true  },
    proReward:   { type: 'xp',             amount: 3000 },
  },
  {
    level: 20,
    freeMission: { title: 'Survival Medio',        desc: 'Sobrevive 50 rondas en Survival',                                enabled: true  },
    freeReward:  { type: 'title',          name: 'Bear Hunter' },
    proMission:  { title: 'Campeón Torneo',        desc: 'Gana un torneo semanal',                                         enabled: true  },
    proReward:   { type: 'mechanic', id: 'mechanic_verified_badge',   name: 'Insignia Verificada' },
  },
  {
    level: 21,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Arena Experto',         desc: 'Gana 30 duelos en Arena contra jugadores reales',                 enabled: true  },
    proReward:   { type: 'xp',             amount: 4000 },
  },
  {
    level: 22,
    freeMission: { title: 'Desafíos Masivos',      desc: 'Completa 20 Daily Challenges',                                   enabled: true  },
    freeReward:  { type: 'xp',             amount: 2000 },
    proMission:  { title: 'Racha Classic',         desc: 'Acierta 20 rondas seguidas en Classic',                          enabled: true  },
    proReward:   { type: 'theme',          name: 'Aurora' },
  },
  {
    level: 23,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Racha 45 Días',         desc: 'Mantén una racha de 45 días',                                    enabled: true  },
    proReward:   { type: 'username_color', id: 'color_purple', name: 'Morado', hex: '#a855f7' },
  },
  {
    level: 24,
    freeMission: { title: 'Racha 14 Días',         desc: 'Mantén una racha de 14 días',                                    enabled: true  },
    freeReward:  { type: 'title',          name: 'Survivor' },
    proMission:  { title: 'Ranking Top 5',         desc: 'Llega al top 5 del ranking semanal',                             enabled: true  },
    proReward:   { type: 'frame',          name: 'Season 1' },
  },
  {
    level: 25,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Desafíos Masivos',      desc: 'Completa 50 Daily Challenges',                                   enabled: true  },
    proReward:   { type: 'mechanic', id: 'mechanic_portfolio_double', name: 'Portfolio Duplicado' },
  },
  {
    level: 26,
    freeMission: { title: 'Duelos en Arena',       desc: 'Gana 3 duelos en Arena contra jugadores reales',                 enabled: true  },
    freeReward:  { type: 'xp',             amount: 2500 },
    proMission:  { title: 'Rentabilidad +50%',     desc: 'Alcanza +50% de rentabilidad en tu cuenta de Trading',           enabled: false },
    proReward:   { type: 'xp',             amount: 5000 },
  },
  {
    level: 27,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Survival Épico',        desc: 'Sobrevive 150 rondas en Survival',                               enabled: true  },
    proReward:   { type: 'avatar', id: 'avatar_dragon', name: 'Dragon' },
  },
  {
    level: 28,
    freeMission: { title: 'Desafíos Diarios',      desc: 'Completa 40 Daily Challenges',                                   enabled: true  },
    freeReward:  { type: 'title',          name: 'Veteran' },
    proMission:  { title: 'Racha 60 Días',         desc: 'Mantén una racha de 60 días',                                    enabled: true  },
    proReward:   { type: 'xp',             amount: 7000 },
  },
  {
    level: 29,
    freeMission: null,
    freeReward:  null,
    proMission:  { title: 'Ranking Top 3',         desc: 'Llega al top 3 del ranking semanal',                             enabled: true  },
    proReward:   { type: 'xp',             amount: 10000 },
  },
  {
    level: 30,
    freeMission: { title: 'Misiones Free',         desc: 'Completa todas las misiones anteriores del Free Track',          enabled: true  },
    freeReward:  { type: 'badge',          name: 'Season 1',            emoji: '🏅' },
    proMission:  { title: 'Misiones Pro',          desc: 'Completa todas las misiones anteriores del Pro Track',           enabled: true  },
    proReward:   { type: 'badge',          name: 'Season 1 Champion',   emoji: '🏆' },
  },
];
