export const ASSET_INFO = {
  // ── Acciones US ──────────────────────────────────────────────────
  AAPL: {
    sector: 'Technology',
    country: 'USA',
    cap: '$2.8T',
    en: 'Apple is the world\'s most valuable company, known for the iPhone, Mac, and App Store ecosystem.',
    es: 'Apple es la empresa más valiosa del mundo, conocida por el iPhone, Mac y el ecosistema App Store.',
    de: 'Apple ist das wertvollste Unternehmen der Welt, bekannt für iPhone, Mac und das App Store-Ökosystem.',
  },
  MSFT: {
    sector: 'Technology',
    country: 'USA',
    cap: '$3.1T',
    en: 'Microsoft dominates enterprise software with Windows, Office, and Azure cloud services.',
    es: 'Microsoft domina el software empresarial con Windows, Office y los servicios cloud Azure.',
    de: 'Microsoft dominiert Unternehmenssoftware mit Windows, Office und Azure-Cloud-Diensten.',
  },
  NVDA: {
    sector: 'Semiconductors',
    country: 'USA',
    cap: '$2.2T',
    en: 'NVIDIA leads the AI chip revolution with its GPUs powering data centers and AI models worldwide.',
    es: 'NVIDIA lidera la revolución de chips IA con sus GPUs que impulsan centros de datos y modelos de IA.',
    de: 'NVIDIA führt die KI-Chip-Revolution mit GPUs an, die Rechenzentren und KI-Modelle weltweit antreiben.',
  },
  GOOGL: {
    sector: 'Technology',
    country: 'USA',
    cap: '$2.0T',
    en: 'Alphabet owns Google Search, YouTube, and Google Cloud — the backbone of the modern internet.',
    es: 'Alphabet es dueña de Google Search, YouTube y Google Cloud — la columna vertebral de internet.',
    de: 'Alphabet besitzt Google Search, YouTube und Google Cloud — das Rückgrat des modernen Internets.',
  },
  AMZN: {
    sector: 'E-Commerce / Cloud',
    country: 'USA',
    cap: '$2.1T',
    en: 'Amazon is the world\'s largest online retailer and cloud provider through AWS.',
    es: 'Amazon es el mayor minorista online del mundo y proveedor de cloud a través de AWS.',
    de: 'Amazon ist der weltgrößte Online-Händler und Cloud-Anbieter durch AWS.',
  },
  META: {
    sector: 'Social Media',
    country: 'USA',
    cap: '$1.4T',
    en: 'Meta owns Facebook, Instagram, and WhatsApp, reaching over 3 billion people daily.',
    es: 'Meta es dueña de Facebook, Instagram y WhatsApp, llegando a más de 3.000 millones de personas al día.',
    de: 'Meta besitzt Facebook, Instagram und WhatsApp und erreicht täglich über 3 Milliarden Menschen.',
  },
  TSLA: {
    sector: 'Electric Vehicles',
    country: 'USA',
    cap: '$800B',
    en: 'Tesla is the world leader in electric vehicles and energy storage, led by Elon Musk.',
    es: 'Tesla es el líder mundial en vehículos eléctricos y almacenamiento de energía, liderada por Elon Musk.',
    de: 'Tesla ist der Weltmarktführer bei Elektrofahrzeugen und Energiespeicherung, geführt von Elon Musk.',
  },
  'BRK.B': {
    sector: 'Financials',
    country: 'USA',
    cap: '$900B',
    en: 'Berkshire Hathaway is Warren Buffett\'s conglomerate holding stakes in Apple, Coca-Cola, and hundreds of companies.',
    es: 'Berkshire Hathaway es el conglomerado de Warren Buffett con participaciones en Apple, Coca-Cola y cientos de empresas.',
    de: 'Berkshire Hathaway ist Warren Buffetts Konglomerat mit Beteiligungen an Apple, Coca-Cola und Hunderten von Unternehmen.',
  },
  JPM: {
    sector: 'Banking',
    country: 'USA',
    cap: '$700B',
    en: 'JPMorgan Chase is the largest US bank by assets, leading in investment banking and retail finance.',
    es: 'JPMorgan Chase es el mayor banco de EE.UU. por activos, líder en banca de inversión y finanzas minoristas.',
    de: 'JPMorgan Chase ist die größte US-Bank nach Vermögenswerten, führend in Investmentbanking und Privatkundengeschäft.',
  },
  V: {
    sector: 'Payments',
    country: 'USA',
    cap: '$550B',
    en: 'Visa operates the world\'s largest payment network, processing billions of transactions daily.',
    es: 'Visa opera la mayor red de pagos del mundo, procesando miles de millones de transacciones al día.',
    de: 'Visa betreibt das weltweit größte Zahlungsnetzwerk und verarbeitet täglich Milliarden von Transaktionen.',
  },
  UNH: {
    sector: 'Healthcare',
    country: 'USA',
    cap: '$450B',
    en: 'UnitedHealth is America\'s largest health insurer, covering over 50 million people.',
    es: 'UnitedHealth es la mayor aseguradora de salud de América, cubriendo a más de 50 millones de personas.',
    de: 'UnitedHealth ist Amerikas größter Krankenversicherer und deckt über 50 Millionen Menschen ab.',
  },
  MA: {
    sector: 'Payments',
    country: 'USA',
    cap: '$430B',
    en: 'Mastercard is a global payment technology company connecting billions of consumers and merchants.',
    es: 'Mastercard es una empresa global de tecnología de pagos que conecta miles de millones de consumidores y comerciantes.',
    de: 'Mastercard ist ein globales Zahlungstechnologieunternehmen, das Milliarden von Verbrauchern und Händlern verbindet.',
  },
  JNJ: {
    sector: 'Healthcare',
    country: 'USA',
    cap: '$380B',
    en: 'Johnson & Johnson is a healthcare giant producing pharmaceuticals, medical devices, and consumer products.',
    es: 'Johnson & Johnson es un gigante de la salud que produce fármacos, dispositivos médicos y productos de consumo.',
    de: 'Johnson & Johnson ist ein Gesundheitsriese, der Pharmazeutika, Medizinprodukte und Konsumgüter herstellt.',
  },
  PG: {
    sector: 'Consumer Staples',
    country: 'USA',
    cap: '$370B',
    en: 'Procter & Gamble owns brands like Gillette, Pampers, and Tide, sold in 180+ countries.',
    es: 'Procter & Gamble es dueña de marcas como Gillette, Pampers y Tide, vendidas en más de 180 países.',
    de: 'Procter & Gamble besitzt Marken wie Gillette, Pampers und Tide, die in über 180 Ländern verkauft werden.',
  },
  HD: {
    sector: 'Retail',
    country: 'USA',
    cap: '$350B',
    en: 'Home Depot is the largest home improvement retailer in the world with 2,300+ stores.',
    es: 'Home Depot es el mayor minorista de mejoras del hogar del mundo con más de 2.300 tiendas.',
    de: 'Home Depot ist der weltgrößte Heimwerkereinzelhändler mit über 2.300 Filialen.',
  },
  BAC: {
    sector: 'Banking',
    country: 'USA',
    cap: '$310B',
    en: 'Bank of America serves 66 million clients and is one of the largest banks in the world.',
    es: 'Bank of America atiende a 66 millones de clientes y es uno de los mayores bancos del mundo.',
    de: 'Bank of America betreut 66 Millionen Kunden und ist eine der größten Banken der Welt.',
  },
  COST: {
    sector: 'Retail',
    country: 'USA',
    cap: '$390B',
    en: 'Costco is a membership-based warehouse retailer known for bulk products and unbeatable prices.',
    es: 'Costco es un minorista de almacén por membresía conocido por productos a granel y precios imbatibles.',
    de: 'Costco ist ein mitgliedschaftsbasierter Lagereinzelhändler, bekannt für Großprodukte und unschlagbare Preise.',
  },
  NFLX: {
    sector: 'Streaming',
    country: 'USA',
    cap: '$290B',
    en: 'Netflix is the world\'s leading streaming platform with 260+ million subscribers globally.',
    es: 'Netflix es la plataforma de streaming líder en el mundo con más de 260 millones de suscriptores.',
    de: 'Netflix ist die weltweit führende Streaming-Plattform mit über 260 Millionen Abonnenten weltweit.',
  },
  ADBE: {
    sector: 'Software',
    country: 'USA',
    cap: '$200B',
    en: 'Adobe dominates creative software with Photoshop, Illustrator, and the PDF standard.',
    es: 'Adobe domina el software creativo con Photoshop, Illustrator y el estándar PDF.',
    de: 'Adobe dominiert Kreativsoftware mit Photoshop, Illustrator und dem PDF-Standard.',
  },
  CRM: {
    sector: 'Software',
    country: 'USA',
    cap: '$240B',
    en: 'Salesforce is the world\'s #1 CRM platform, helping companies manage customer relationships.',
    es: 'Salesforce es la plataforma CRM nº 1 del mundo, ayudando a las empresas a gestionar relaciones con clientes.',
    de: 'Salesforce ist die weltweit führende CRM-Plattform und hilft Unternehmen, Kundenbeziehungen zu verwalten.',
  },
  AMD: {
    sector: 'Semiconductors',
    country: 'USA',
    cap: '$230B',
    en: 'AMD makes high-performance CPUs and GPUs competing directly with Intel and NVIDIA.',
    es: 'AMD fabrica CPUs y GPUs de alto rendimiento compitiendo directamente con Intel y NVIDIA.',
    de: 'AMD stellt Hochleistungs-CPUs und GPUs her und konkurriert direkt mit Intel und NVIDIA.',
  },
  ORCL: {
    sector: 'Software / Cloud',
    country: 'USA',
    cap: '$360B',
    en: 'Oracle is a cloud computing and database giant trusted by most of the world\'s largest companies.',
    es: 'Oracle es un gigante del cloud y bases de datos en el que confían la mayoría de las mayores empresas del mundo.',
    de: 'Oracle ist ein Cloud- und Datenbankgigant, dem die meisten der weltgrößten Unternehmen vertrauen.',
  },
  UBER: {
    sector: 'Transport / Tech',
    country: 'USA',
    cap: '$160B',
    en: 'Uber is the world\'s largest ride-hailing and food delivery platform, operating in 70+ countries.',
    es: 'Uber es la mayor plataforma de transporte y entrega de comida del mundo, operando en más de 70 países.',
    de: 'Uber ist die weltweit größte Fahrvermittlungs- und Essenslieferplattform in über 70 Ländern.',
  },
  PYPL: {
    sector: 'Fintech',
    country: 'USA',
    cap: '$65B',
    en: 'PayPal is a leading digital payments platform with 430+ million active accounts worldwide.',
    es: 'PayPal es una plataforma líder de pagos digitales con más de 430 millones de cuentas activas en el mundo.',
    de: 'PayPal ist eine führende digitale Zahlungsplattform mit über 430 Millionen aktiven Konten weltweit.',
  },
  INTC: {
    sector: 'Semiconductors',
    country: 'USA',
    cap: '$85B',
    en: 'Intel is the world\'s largest semiconductor company by revenue, known for PC and server processors.',
    es: 'Intel es la mayor empresa de semiconductores del mundo por ingresos, conocida por procesadores de PC y servidor.',
    de: 'Intel ist das weltweit größte Halbleiterunternehmen nach Umsatz, bekannt für PC- und Serverprozessoren.',
  },
  SPOT: {
    sector: 'Streaming',
    country: 'Sweden',
    cap: '$70B',
    en: 'Spotify is the world\'s largest music streaming platform with 600+ million users.',
    es: 'Spotify es la mayor plataforma de streaming musical del mundo con más de 600 millones de usuarios.',
    de: 'Spotify ist die weltweit größte Musik-Streaming-Plattform mit über 600 Millionen Nutzern.',
  },
  ABNB: {
    sector: 'Travel / Tech',
    country: 'USA',
    cap: '$80B',
    en: 'Airbnb revolutionized travel with its peer-to-peer home rental platform in 220+ countries.',
    es: 'Airbnb revolucionó los viajes con su plataforma de alquiler de casas entre particulares en más de 220 países.',
    de: 'Airbnb revolutionierte das Reisen mit seiner Peer-to-Peer-Mietwohnungsplattform in über 220 Ländern.',
  },
  SHOP: {
    sector: 'E-Commerce',
    country: 'Canada',
    cap: '$110B',
    en: 'Shopify powers over 1.7 million businesses worldwide with its e-commerce platform.',
    es: 'Shopify impulsa a más de 1,7 millones de negocios en todo el mundo con su plataforma de e-commerce.',
    de: 'Shopify unterstützt über 1,7 Millionen Unternehmen weltweit mit seiner E-Commerce-Plattform.',
  },
  PLTR: {
    sector: 'AI / Defense',
    country: 'USA',
    cap: '$150B',
    en: 'Palantir builds AI-powered data analytics platforms for governments and large enterprises.',
    es: 'Palantir construye plataformas de análisis de datos con IA para gobiernos y grandes empresas.',
    de: 'Palantir entwickelt KI-gestützte Datenanalyseplattformen für Regierungen und Großunternehmen.',
  },
  COIN: {
    sector: 'Crypto / Fintech',
    country: 'USA',
    cap: '$55B',
    en: 'Coinbase is the largest US crypto exchange, acting as a gateway to the crypto market.',
    es: 'Coinbase es el mayor exchange de cripto de EE.UU., actuando como puerta de entrada al mercado cripto.',
    de: 'Coinbase ist die größte US-Kryptobörse und dient als Einstiegspunkt in den Kryptomarkt.',
  },
  HOOD: {
    sector: 'Fintech',
    country: 'USA',
    cap: '$20B',
    en: 'Robinhood democratized investing by offering commission-free trades to retail investors.',
    es: 'Robinhood democratizó la inversión ofreciendo operaciones sin comisiones a inversores minoristas.',
    de: 'Robinhood demokratisierte das Investieren durch provisionsfreie Trades für Privatanleger.',
  },
  NET: {
    sector: 'Cybersecurity',
    country: 'USA',
    cap: '$65B',
    en: 'Cloudflare protects and accelerates millions of websites with its global network infrastructure.',
    es: 'Cloudflare protege y acelera millones de sitios web con su infraestructura de red global.',
    de: 'Cloudflare schützt und beschleunigt Millionen von Websites mit seiner globalen Netzwerkinfrastruktur.',
  },
  MSTR: {
    sector: 'Technology / Bitcoin',
    country: 'USA',
    cap: '$90B',
    en: 'MicroStrategy holds over 200,000 Bitcoin on its balance sheet, making it a de facto Bitcoin proxy stock.',
    es: 'MicroStrategy tiene más de 200.000 Bitcoin en su balance, convirtiéndola en una acción proxy de Bitcoin.',
    de: 'MicroStrategy hält über 200.000 Bitcoin in seiner Bilanz und ist damit ein De-facto-Bitcoin-Proxy.',
  },
  ARM: {
    sector: 'Semiconductors',
    country: 'UK',
    cap: '$130B',
    en: 'ARM designs the chip architecture found in virtually every smartphone on the planet.',
    es: 'ARM diseña la arquitectura de chips que se encuentra en prácticamente todos los smartphones del planeta.',
    de: 'ARM entwickelt die Chip-Architektur, die sich in praktisch jedem Smartphone auf dem Planeten befindet.',
  },
  TSM: {
    sector: 'Semiconductors',
    country: 'Taiwan',
    cap: '$900B',
    en: 'TSMC manufactures chips for Apple, NVIDIA, and AMD — controlling over 50% of the global foundry market.',
    es: 'TSMC fabrica chips para Apple, NVIDIA y AMD — controlando más del 50% del mercado global de fundición.',
    de: 'TSMC stellt Chips für Apple, NVIDIA und AMD her und kontrolliert über 50% des globalen Foundry-Markts.',
  },
  SMCI: {
    sector: 'AI Infrastructure',
    country: 'USA',
    cap: '$30B',
    en: 'Super Micro builds high-performance servers for AI data centers, riding the GPU compute wave.',
    es: 'Super Micro construye servidores de alto rendimiento para centros de datos de IA, montada en la ola del cómputo GPU.',
    de: 'Super Micro baut Hochleistungsserver für KI-Rechenzentren und reitet die GPU-Computing-Welle.',
  },
  APP: {
    sector: 'AdTech / AI',
    country: 'USA',
    cap: '$120B',
    en: 'AppLovin is the fastest-growing adtech company, using AI to power mobile app advertising.',
    es: 'AppLovin es la empresa de adtech de más rápido crecimiento, usando IA para impulsar la publicidad en apps móviles.',
    de: 'AppLovin ist das am schnellsten wachsende Adtech-Unternehmen, das KI für mobile App-Werbung nutzt.',
  },
  MELI: {
    sector: 'E-Commerce',
    country: 'Argentina',
    cap: '$100B',
    en: 'MercadoLibre is the Amazon of Latin America, dominating e-commerce and fintech across 18 countries.',
    es: 'MercadoLibre es el Amazon de Latinoamérica, dominando el e-commerce y fintech en 18 países.',
    de: 'MercadoLibre ist das Amazon Lateinamerikas und dominiert E-Commerce und Fintech in 18 Ländern.',
  },

  // ── Acciones europeas ─────────────────────────────────────────────
  ASML: {
    sector: 'Semiconductors',
    country: 'Netherlands',
    cap: '$280B',
    en: 'ASML is the only company in the world that makes EUV machines — the tools that print the most advanced chips.',
    es: 'ASML es la única empresa del mundo que fabrica máquinas EUV — las herramientas que imprimen los chips más avanzados.',
    de: 'ASML ist das einzige Unternehmen weltweit, das EUV-Maschinen herstellt — die Werkzeuge für modernste Chips.',
  },
  SAP: {
    sector: 'Enterprise Software',
    country: 'Germany',
    cap: '$230B',
    en: 'SAP is Europe\'s largest software company, powering ERP systems for 99% of Fortune 500 companies.',
    es: 'SAP es la mayor empresa de software de Europa, impulsando sistemas ERP para el 99% de las empresas Fortune 500.',
    de: 'SAP ist Europas größtes Softwareunternehmen und treibt ERP-Systeme für 99% der Fortune-500-Unternehmen an.',
  },
  LVMUY: {
    sector: 'Luxury',
    country: 'France',
    cap: '$290B',
    en: 'LVMH is the world\'s largest luxury group, owning Louis Vuitton, Dior, Moët, and 75+ premium brands.',
    es: 'LVMH es el mayor grupo de lujo del mundo, dueño de Louis Vuitton, Dior, Moët y más de 75 marcas premium.',
    de: 'LVMH ist die weltgrößte Luxusgruppe mit Louis Vuitton, Dior, Moët und über 75 Premiummarken.',
  },
  NSRGY: {
    sector: 'Consumer Staples',
    country: 'Switzerland',
    cap: '$230B',
    en: 'Nestlé is the world\'s largest food company, owning Nespresso, KitKat, Maggi, and hundreds of brands.',
    es: 'Nestlé es la mayor empresa de alimentación del mundo, dueña de Nespresso, KitKat, Maggi y cientos de marcas.',
    de: 'Nestlé ist das weltgrößte Lebensmittelunternehmen mit Nespresso, KitKat, Maggi und Hunderten von Marken.',
  },
  SIEGY: {
    sector: 'Industrial',
    country: 'Germany',
    cap: '$140B',
    en: 'Siemens is a global industrial conglomerate leading in automation, energy, and smart infrastructure.',
    es: 'Siemens es un conglomerado industrial global líder en automatización, energía e infraestructura inteligente.',
    de: 'Siemens ist ein globales Industriekonglomerat, führend in Automatisierung, Energie und intelligenter Infrastruktur.',
  },
  IDEXY: {
    sector: 'Fashion / Retail',
    country: 'Spain',
    cap: '$120B',
    en: 'Inditex owns Zara, Massimo Dutti, and Pull&Bear — the world\'s largest fast fashion group.',
    es: 'Inditex es dueña de Zara, Massimo Dutti y Pull&Bear — el mayor grupo de moda rápida del mundo.',
    de: 'Inditex besitzt Zara, Massimo Dutti und Pull&Bear — die weltgrößte Fast-Fashion-Gruppe.',
  },
  ALIZF: {
    sector: 'Insurance',
    country: 'Germany',
    cap: '$110B',
    en: 'Allianz is Europe\'s largest insurance company, operating in 70+ countries worldwide.',
    es: 'Allianz es la mayor aseguradora de Europa, operando en más de 70 países en todo el mundo.',
    de: 'Allianz ist Europas größtes Versicherungsunternehmen und operiert in über 70 Ländern weltweit.',
  },
  BAYZF: {
    sector: 'Pharmaceuticals',
    country: 'Germany',
    cap: '$28B',
    en: 'Bayer is a global pharmaceutical and agricultural company known for aspirin and crop science.',
    es: 'Bayer es una empresa farmacéutica y agrícola global conocida por la aspirina y la ciencia agrícola.',
    de: 'Bayer ist ein globales Pharma- und Agrochemieunternehmen, bekannt für Aspirin und Pflanzenwissenschaften.',
  },
  RACE: {
    sector: 'Luxury / Automotive',
    country: 'Italy',
    cap: '$75B',
    en: 'Ferrari is the world\'s most powerful luxury brand, selling exclusivity as much as cars.',
    es: 'Ferrari es la marca de lujo más poderosa del mundo, vendiendo exclusividad tanto como coches.',
    de: 'Ferrari ist die mächtigste Luxusmarke der Welt und verkauft Exklusivität genauso wie Autos.',
  },

  // ── Índices y ETFs ────────────────────────────────────────────────
  SPY: {
    sector: 'Index ETF',
    country: 'USA',
    cap: '$550B AUM',
    en: 'SPY tracks the S&P 500 — the 500 largest US companies. The benchmark for the US stock market.',
    es: 'SPY sigue el S&P 500 — las 500 mayores empresas de EE.UU. El referente del mercado bursátil estadounidense.',
    de: 'SPY bildet den S&P 500 ab — die 500 größten US-Unternehmen. Der Maßstab für den US-Aktienmarkt.',
  },
  QQQ: {
    sector: 'Index ETF',
    country: 'USA',
    cap: '$260B AUM',
    en: 'QQQ tracks the NASDAQ 100, the 100 largest non-financial companies including Apple, NVIDIA, and Google.',
    es: 'QQQ sigue el NASDAQ 100, las 100 mayores empresas no financieras incluyendo Apple, NVIDIA y Google.',
    de: 'QQQ bildet den NASDAQ 100 ab, die 100 größten Nicht-Finanzunternehmen einschließlich Apple, NVIDIA und Google.',
  },
  DIA: {
    sector: 'Index ETF',
    country: 'USA',
    cap: '$35B AUM',
    en: 'DIA tracks the Dow Jones Industrial Average — 30 blue-chip US companies like Boeing, Goldman Sachs, and Nike.',
    es: 'DIA sigue el Dow Jones Industrial Average — 30 empresas blue-chip de EE.UU. como Boeing, Goldman Sachs y Nike.',
    de: 'DIA bildet den Dow Jones Industrial Average ab — 30 Blue-Chip-US-Unternehmen wie Boeing, Goldman Sachs und Nike.',
  },
  VTI: {
    sector: 'Index ETF',
    country: 'USA',
    cap: '$430B AUM',
    en: 'VTI tracks the entire US stock market — over 3,500 companies from large-cap to small-cap.',
    es: 'VTI sigue todo el mercado bursátil de EE.UU. — más de 3.500 empresas desde large-cap hasta small-cap.',
    de: 'VTI bildet den gesamten US-Aktienmarkt ab — über 3.500 Unternehmen von Large-Cap bis Small-Cap.',
  },
  VOO: {
    sector: 'Index ETF',
    country: 'USA',
    cap: '$550B AUM',
    en: 'VOO is Vanguard\'s S&P 500 ETF — one of the most popular long-term investment vehicles in the world.',
    es: 'VOO es el ETF del S&P 500 de Vanguard — uno de los vehículos de inversión a largo plazo más populares del mundo.',
    de: 'VOO ist Vanguards S&P 500 ETF — eines der beliebtesten langfristigen Anlageinstrumente der Welt.',
  },
  IWM: {
    sector: 'Index ETF',
    country: 'USA',
    cap: '$65B AUM',
    en: 'IWM tracks the Russell 2000 — 2,000 small-cap US companies, a gauge of domestic economic health.',
    es: 'IWM sigue el Russell 2000 — 2.000 empresas small-cap de EE.UU., un indicador de la salud económica doméstica.',
    de: 'IWM bildet den Russell 2000 ab — 2.000 Small-Cap-US-Unternehmen, ein Maßstab für die inländische Wirtschaftsgesundheit.',
  },
  VEA: {
    sector: 'Index ETF',
    country: 'International',
    cap: '$120B AUM',
    en: 'VEA tracks developed market stocks outside the US — Europe, Japan, Australia, and Canada.',
    es: 'VEA sigue acciones de mercados desarrollados fuera de EE.UU. — Europa, Japón, Australia y Canadá.',
    de: 'VEA bildet Aktien entwickelter Märkte außerhalb der USA ab — Europa, Japan, Australien und Kanada.',
  },
  VWO: {
    sector: 'Index ETF',
    country: 'Emerging Markets',
    cap: '$80B AUM',
    en: 'VWO tracks emerging market stocks from China, India, Brazil, Taiwan, and other growing economies.',
    es: 'VWO sigue acciones de mercados emergentes de China, India, Brasil, Taiwán y otras economías en crecimiento.',
    de: 'VWO bildet Schwellenmarktaktien aus China, Indien, Brasilien, Taiwan und anderen wachsenden Volkswirtschaften ab.',
  },
  EWG: {
    sector: 'Country ETF',
    country: 'Germany',
    cap: '$2B AUM',
    en: 'EWG tracks the German stock market — Europe\'s largest economy with companies like SAP and Siemens.',
    es: 'EWG sigue el mercado bursátil alemán — la mayor economía de Europa con empresas como SAP y Siemens.',
    de: 'EWG bildet den deutschen Aktienmarkt ab — Europas größte Volkswirtschaft mit Unternehmen wie SAP und Siemens.',
  },
  EWQ: {
    sector: 'Country ETF',
    country: 'France',
    cap: '$600M AUM',
    en: 'EWQ tracks the French stock market, home to luxury giants like LVMH and L\'Oréal.',
    es: 'EWQ sigue el mercado bursátil francés, hogar de gigantes del lujo como LVMH y L\'Oréal.',
    de: 'EWQ bildet den französischen Aktienmarkt ab, Heimat von Luxusgiganten wie LVMH und L\'Oréal.',
  },
  EWP: {
    sector: 'Country ETF',
    country: 'Spain',
    cap: '$500M AUM',
    en: 'EWP tracks the Spanish stock market, including Inditex, Santander, and Iberdrola.',
    es: 'EWP sigue el mercado bursátil español, incluyendo Inditex, Santander e Iberdrola.',
    de: 'EWP bildet den spanischen Aktienmarkt ab, einschließlich Inditex, Santander und Iberdrola.',
  },
  ARKK: {
    sector: 'Thematic ETF',
    country: 'USA',
    cap: '$6B AUM',
    en: 'ARK Innovation ETF invests in disruptive technologies like AI, genomics, and blockchain.',
    es: 'ARK Innovation ETF invierte en tecnologías disruptivas como IA, genómica y blockchain.',
    de: 'ARK Innovation ETF investiert in disruptive Technologien wie KI, Genomik und Blockchain.',
  },
  XLK: {
    sector: 'Sector ETF',
    country: 'USA',
    cap: '$65B AUM',
    en: 'XLK tracks the US technology sector — Apple, Microsoft, and NVIDIA make up over 40% of the fund.',
    es: 'XLK sigue el sector tecnológico de EE.UU. — Apple, Microsoft y NVIDIA suponen más del 40% del fondo.',
    de: 'XLK bildet den US-Technologiesektor ab — Apple, Microsoft und NVIDIA machen über 40% des Fonds aus.',
  },
  XLF: {
    sector: 'Sector ETF',
    country: 'USA',
    cap: '$45B AUM',
    en: 'XLF tracks US financial stocks — banks, insurance companies, and asset managers.',
    es: 'XLF sigue las acciones financieras de EE.UU. — bancos, aseguradoras y gestores de activos.',
    de: 'XLF bildet US-Finanzaktien ab — Banken, Versicherungen und Vermögensverwalter.',
  },
  XLE: {
    sector: 'Sector ETF',
    country: 'USA',
    cap: '$30B AUM',
    en: 'XLE tracks the US energy sector — ExxonMobil, Chevron, and other oil & gas companies.',
    es: 'XLE sigue el sector energético de EE.UU. — ExxonMobil, Chevron y otras empresas de petróleo y gas.',
    de: 'XLE bildet den US-Energiesektor ab — ExxonMobil, Chevron und andere Öl- und Gasunternehmen.',
  },
  XLV: {
    sector: 'Sector ETF',
    country: 'USA',
    cap: '$38B AUM',
    en: 'XLV tracks US healthcare stocks — pharmaceuticals, hospitals, and medical device companies.',
    es: 'XLV sigue las acciones sanitarias de EE.UU. — farmacéuticas, hospitales y empresas de dispositivos médicos.',
    de: 'XLV bildet US-Gesundheitsaktien ab — Pharmaunternehmen, Krankenhäuser und Medizingerätehersteller.',
  },
  TLT: {
    sector: 'Bond ETF',
    country: 'USA',
    cap: '$50B AUM',
    en: 'TLT tracks long-term US government bonds (20+ years). It rises when interest rates fall.',
    es: 'TLT sigue los bonos del gobierno de EE.UU. a largo plazo (+20 años). Sube cuando los tipos de interés bajan.',
    de: 'TLT bildet langfristige US-Staatsanleihen (20+ Jahre) ab. Er steigt, wenn die Zinsen fallen.',
  },
  AGG: {
    sector: 'Bond ETF',
    country: 'USA',
    cap: '$100B AUM',
    en: 'AGG tracks the total US bond market — a diversified mix of government, corporate, and mortgage bonds.',
    es: 'AGG sigue el mercado total de bonos de EE.UU. — una mezcla diversificada de bonos gubernamentales, corporativos e hipotecarios.',
    de: 'AGG bildet den gesamten US-Anleihemarkt ab — eine diversifizierte Mischung aus Staats-, Unternehmens- und Hypothekenanleihen.',
  },
  HYG: {
    sector: 'Bond ETF',
    country: 'USA',
    cap: '$14B AUM',
    en: 'HYG tracks high-yield corporate bonds — higher returns than government bonds but with more risk.',
    es: 'HYG sigue bonos corporativos de alto rendimiento — mayores retornos que los bonos gubernamentales pero con más riesgo.',
    de: 'HYG bildet Hochzinsunternehmensanleihen ab — höhere Renditen als Staatsanleihen, aber mit mehr Risiko.',
  },
  BOTZ: {
    sector: 'Thematic ETF',
    country: 'USA',
    cap: '$2B AUM',
    en: 'BOTZ invests in robotics and AI companies — industrial robots, autonomous vehicles, and machine learning.',
    es: 'BOTZ invierte en empresas de robótica e IA — robots industriales, vehículos autónomos y aprendizaje automático.',
    de: 'BOTZ investiert in Robotik- und KI-Unternehmen — Industrieroboter, autonome Fahrzeuge und maschinelles Lernen.',
  },
  HERO: {
    sector: 'Thematic ETF',
    country: 'USA',
    cap: '$300M AUM',
    en: 'HERO tracks the global gaming and esports industry — game developers, streaming platforms, and hardware makers.',
    es: 'HERO sigue la industria global de videojuegos y esports — desarrolladores, plataformas de streaming y fabricantes de hardware.',
    de: 'HERO bildet die globale Gaming- und Esports-Industrie ab — Spieleentwickler, Streaming-Plattformen und Hardware-Hersteller.',
  },
  ICLN: {
    sector: 'Thematic ETF',
    country: 'USA',
    cap: '$2B AUM',
    en: 'ICLN invests in global clean energy companies — solar, wind, and other renewable energy producers.',
    es: 'ICLN invierte en empresas globales de energía limpia — solar, eólica y otros productores de energías renovables.',
    de: 'ICLN investiert in globale Unternehmen für saubere Energie — Solar-, Wind- und andere erneuerbare Energieproduzenten.',
  },

  // ── Cripto ────────────────────────────────────────────────────────
  BTCUSDT: {
    sector: 'Cryptocurrency',
    country: 'Decentralized',
    cap: '$1.5T',
    en: 'Bitcoin is the world\'s first and largest cryptocurrency, created in 2009 by Satoshi Nakamoto.',
    es: 'Bitcoin es la primera y mayor criptomoneda del mundo, creada en 2009 por Satoshi Nakamoto.',
    de: 'Bitcoin ist die erste und größte Kryptowährung der Welt, 2009 von Satoshi Nakamoto erschaffen.',
  },
  ETHUSDT: {
    sector: 'Cryptocurrency',
    country: 'Decentralized',
    cap: '$300B',
    en: 'Ethereum is the leading smart contract platform powering DeFi, NFTs, and most of the crypto ecosystem.',
    es: 'Ethereum es la plataforma líder de contratos inteligentes que impulsa DeFi, NFTs y la mayor parte del ecosistema cripto.',
    de: 'Ethereum ist die führende Smart-Contract-Plattform, die DeFi, NFTs und den größten Teil des Krypto-Ökosystems antreibt.',
  },
  XRPUSDT: {
    sector: 'Cryptocurrency',
    country: 'Decentralized',
    cap: '$130B',
    en: 'XRP is designed for fast, low-cost international payments between banks and financial institutions.',
    es: 'XRP está diseñado para pagos internacionales rápidos y de bajo coste entre bancos e instituciones financieras.',
    de: 'XRP ist für schnelle, kostengünstige internationale Zahlungen zwischen Banken und Finanzinstitutionen konzipiert.',
  },
  SOLUSDT: {
    sector: 'Cryptocurrency',
    country: 'Decentralized',
    cap: '$65B',
    en: 'Solana is a high-speed blockchain processing 65,000 transactions per second, rivaling Ethereum.',
    es: 'Solana es una blockchain de alta velocidad que procesa 65.000 transacciones por segundo, rivalizando con Ethereum.',
    de: 'Solana ist eine Hochgeschwindigkeits-Blockchain, die 65.000 Transaktionen pro Sekunde verarbeitet und Ethereum rivalisiert.',
  },
  // ── Materias primas ───────────────────────────────────────────────
  GLD: {
    sector: 'Commodity ETF',
    country: 'USA',
    cap: '$70B AUM',
    en: 'GLD tracks the price of gold — the world\'s oldest safe-haven asset used as a hedge against inflation.',
    es: 'GLD sigue el precio del oro — el activo refugio más antiguo del mundo usado como cobertura contra la inflación.',
    de: 'GLD bildet den Goldpreis ab — das älteste Sicherheitsasset der Welt, das als Inflationsschutz eingesetzt wird.',
  },
  SLV: {
    sector: 'Commodity ETF',
    country: 'USA',
    cap: '$13B AUM',
    en: 'SLV tracks silver prices — both a precious metal and industrial commodity used in solar panels and electronics.',
    es: 'SLV sigue el precio de la plata — tanto metal precioso como materia prima industrial usada en paneles solares y electrónica.',
    de: 'SLV bildet den Silberpreis ab — sowohl Edelmetall als auch industrieller Rohstoff für Solarmodule und Elektronik.',
  },
  PDBC: {
    sector: 'Commodity ETF',
    country: 'USA',
    cap: '$5B AUM',
    en: 'PDBC tracks a diversified basket of commodities including oil, gold, wheat, and natural gas.',
    es: 'PDBC sigue una cesta diversificada de materias primas incluyendo petróleo, oro, trigo y gas natural.',
    de: 'PDBC bildet einen diversifizierten Rohstoffkorb einschließlich Öl, Gold, Weizen und Erdgas ab.',
  },
  GDX: {
    sector: 'Commodity ETF',
    country: 'USA',
    cap: '$14B AUM',
    en: 'GDX tracks gold mining companies — when gold prices rise, miners often gain even more.',
    es: 'GDX sigue empresas mineras de oro — cuando el precio del oro sube, las mineras suelen ganar aún más.',
    de: 'GDX bildet Goldminenunternehmen ab — wenn der Goldpreis steigt, gewinnen Minengesellschaften oft noch mehr.',
  },
  PPLT: {
    sector: 'Commodity ETF',
    country: 'USA',
    cap: '$1B AUM',
    en: 'PPLT tracks platinum prices — a rare precious metal used in catalytic converters and jewelry.',
    es: 'PPLT sigue el precio del platino — un metal precioso raro usado en catalizadores y joyería.',
    de: 'PPLT bildet den Platinpreis ab — ein seltenes Edelmetall, das in Katalysatoren und Schmuck verwendet wird.',
  },
  WEAT: {
    sector: 'Commodity ETF',
    country: 'USA',
    cap: '$300M AUM',
    en: 'WEAT tracks wheat futures — one of the world\'s most important food commodities.',
    es: 'WEAT sigue los futuros del trigo — una de las materias primas alimentarias más importantes del mundo.',
    de: 'WEAT bildet Weizen-Futures ab — einen der wichtigsten Nahrungsmittelrohstoffe der Welt.',
  },
  CORN: {
    sector: 'Commodity ETF',
    country: 'USA',
    cap: '$100M AUM',
    en: 'CORN tracks corn futures — used in food, biofuel, and animal feed across the world.',
    es: 'CORN sigue los futuros del maíz — usado en alimentación, biocombustible y piensos en todo el mundo.',
    de: 'CORN bildet Mais-Futures ab — verwendet in Lebensmitteln, Biokraftstoff und Tierfutter weltweit.',
  },
};