import {
  Crosshair, Flame, Brain, Gem, Target,
  Bitcoin, ArrowLeftRight, Globe, Waves,
  CalendarCheck, CalendarHeart, Crown, Sunrise, Zap,
  Calendar, CalendarDays,
  Swords, Skull, ShieldCheck, Megaphone,
  Camera, Medal,
  Scroll, Clock,
  Shield, Sparkles,
  ClipboardList,
  TrendingUp, Rocket, TrendingDown, Activity,
  UserPlus, Users, Trophy, Dumbbell,
  Ghost, Moon, Heart, Banknote, RotateCcw,
  Sword,
} from 'lucide-react';

const BADGE_ICONS = {
  sniper:             Crosshair,
  on_fire:            Flame,
  big_brain:          Brain,
  diamond_hands:      Gem,
  perfectionist:      Target,
  bitcoin_maxi:       Bitcoin,
  forex_king:         ArrowLeftRight,
  all_rounder:        Globe,
  whale:              Waves,
  consistent:         CalendarCheck,
  dedicated:          CalendarHeart,
  legend:             Crown,
  early_bird:         Sunrise,
  perfect_week:       Zap,
  daily_streak_3:     Calendar,
  daily_streak_7:     CalendarDays,
  daily_streak_30:    Crown,
  first_blood:        Swords,
  dominator:          Skull,
  unbeatable:         ShieldCheck,
  recruiter:          Megaphone,
  screenshot_ready:   Camera,
  top_10:             Medal,
  historian:          Scroll,
  time_traveler:      Clock,
  survivor:           Shield,
  immortal:           Sparkles,
  last_stand:         Skull,
  mission_first:      Target,
  mission_week:       ClipboardList,
  mission_master:     Zap,
  portfolio_profit:   TrendingUp,
  portfolio_10x:      Rocket,
  portfolio_loss:     TrendingDown,
  portfolio_diverse:  Globe,
  portfolio_hodl:     Gem,
  portfolio_trader:   Activity,
  social_first:       UserPlus,
  social_squad:       Users,
  social_duel_win:    Swords,
  social_duel_3:      Trophy,
  social_challenger:  Dumbbell,
  streak_14:          Flame,
  streak_60:          Sparkles,
  streak_100:         Crown,
  arena_streak_3:     Swords,
  arena_streak_5:     Sword,
  ghost:              Ghost,
  rekt:               Skull,
  secret_night:       Moon,
  secret_allgreen:    Heart,
  secret_broke:       Banknote,
  secret_speedrun:    Zap,
  secret_comeback:    RotateCcw,
};

export default function BadgeIcon({ id, size = 24 }) {
  const Icon = BADGE_ICONS[id];
  if (!Icon) return null;
  return <Icon size={size} aria-hidden strokeWidth={1.75} />;
}
